<?php
/**
 * WiseSync Plugin Drop-Ins or Mu-Plugin.
 *
 * This File is Generated By WiseSync Plugin with a Fixed Template developed for Drop-Ins or Mu-Plugin,
 * If for any reason there is issue in File, either Delete it and Genrate Again,
 * If issue Still Exist, below try edit $sync_sunrise_path to load in plugin to file ./includes/load/sunrise.php
 *
 * Plugin Name:       WiseSync Sunrise
 * Plugin URI:        https://shubkb.com
 * Description:       Pre-Handle WordPress Multi-Site loading. 
 * Version:           1.0.0
 * Requires at least: 6.8
 * Requires PHP:      8.3
 * Author:            Shubham Kumar Bansal 
 * Author URI:        https://shubkb.com
 * License:           Apache License 2.0
 * License URI:       https://www.apache.org/licenses/LICENSE-2.0
 *
 * @package   WISESYNC
 * @since    1.0.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

define( 'WSYNC_SUNRISE_PRESENT', true );

$sync_sunrise_data = '{"test":"test"}';

// Path to Load File.
$sync_sunrise_path = '/mnt/windows-data/Users/shub/shubham/code/wp/sync/app/public/wp-content/plugins/wisesync/includes/load/sunrise.php';

// Load Main Mu-Plugin File.
if ( file_exists( $sync_sunrise_path ) ) {
	require_once $sync_sunrise_path;
} else {

	// Show Admin Notice, to fix Path to Mu Plugin Load File.
	add_filter(
		'sync_add_admin_notice',
		function ( $admin_notice_callbacks ) {
			global $sync_plugin;
			// Append Call back.
			$admin_notice_callbacks[] = array( $sync_plugin, 'sync_sunrise_on_error' );
			return $admin_notice_callbacks;
		}
	);
}
