blank_issues_enabled: true
contact_links:
  - name: 💬 Ask a Question
    url: https://github.com/shubkb07/shubkb.com/discussions
    about: Ask and discuss things that are not bug reports or feature requests.
