<?php
/**
 * WiseSync Plugin Drop-Ins or Mu-Plugin.
 *
 * This File is Generated By WiseSync Plugin with a Fixed Template developed for Drop-Ins or Mu-Plugin,
 * If for any reason there is issue in File, either Delete it and Genrate Again,
 * If issue Still Exist, below try edit $sync_mu_plugin_path to load in plugin to file ./includes/load/sync.php
 *
 * Plugin Name:       WiseSync Plugin Mu Plugin
 * Plugin URI:        https://shubkb.com
 * Description:       All-in-one solution for WordPress users to use everything WiseSync has to offer to make them successful on the web. 
 * Version:           1.0.0
 * Requires at least: 6.8
 * Requires PHP:      8.3
 * Author:            Shubham Kumar Bansal 
 * Author URI:        https://shubkb.com
 * License:           Apache License 2.0
 * License URI:       https://www.apache.org/licenses/LICENSE-2.0
 *
 * @package   WISESYNC
 * @since    1.0.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

define( 'WSYNC_MU_PLUGIN_PRESENT', true );

$sync_mu_plugin_data = '{"pikachu":"electric","charizard":"fire","bulbasaur":"grass","squirtle":"water","jigglypuff":"normal","meowth":"normal","eevee":"normal","ditto":"normal","psyduck":"water","caterpie":"bug","butterfree":"bug","beedrill":"bug","weedle":"bug","caterpie2":{"butterfree2":"bug","beedrill2":"bug","weedle2":"bug"},"caterpie3":{"butterfree3":"bug","beedrill3":"bug","weedle3":"bug"},"caterpie4":{"butterfree4":"bug","beedrill4":"bug","weedle4":"bug"},"caterpie5":{"butterfree5":"bug","beedrill5":"bug","weedle5":"bug"}}';

// Path to Load File.
$sync_mu_plugin_path = '/mnt/windows-data/Users/shub/shubham/code/wp/sync/app/public/wp-content/mu-plugins/sync.php';

// Load Main Mu-Plugin File.
if ( file_exists( $sync_mu_plugin_path ) ) {
	require_once $sync_mu_plugin_path;
} else {

	// Show Admin Notice, to fix Path to Mu Plugin Load File.
	add_filter(
		'sync_add_admin_notice',
		function ( $admin_notice_callbacks ) {
			global $sync_plugin;
			// Append Call back.
			$admin_notice_callbacks[] = array( $sync_plugin, 'sync_mu_plugin_on_error' );
			return $admin_notice_callbacks;
		}
	);
}
