<?php
/**
 * WiseSync Plugin Drop-Ins or Mu-Plugin.
 *
 * This File is Generated By WiseSync Plugin with a Fixed Template developed for Drop-Ins or Mu-Plugin,
 * If for any reason there is issue in File, either Delete it and Genrate Again,
 * If issue Still Exist, below try edit $sync_{{ACCEPT}}_path to load in plugin to file ./includes/load/{{FILE}}
 *
 * Plugin Name:       {{Name}}
 * Plugin URI:        {{PluginURI}}
 * Description:       {{Description}}
 * Version:           {{Version}}
 * Requires at least: {{RequiresWP}}
 * Requires PHP:      {{RequiresPHP}}
 * Author:            {{AuthorName}}
 * Author URI:        {{AuthorURI}}
 * License:           Apache License 2.0
 * License URI:       https://www.apache.org/licenses/LICENSE-2.0
 *
 * phpcs:disable
 *
 * @package   WISESYNC
 * @since    1.0.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

define( '{{CONSTANT}}_PRESENT', true );

$sync_{{ACCEPT}}_data = '{{FILE_DATA}}';

// Path to Load File.
$sync_{{ACCEPT}}_path = '{{PATH}}/{{FILE}}';

// Load Main Mu-Plugin File.
if ( file_exists( $sync_{{ACCEPT}}_path ) ) {
	require_once $sync_{{ACCEPT}}_path;
} else {

	// Show Admin Notice, to fix Path to Mu Plugin Load File.
	add_filter(
		'sync_add_admin_notice',
		function ( $admin_notice_callbacks ) {
			global $sync_plugin;
			// Append Call back.
			$admin_notice_callbacks[] = array( $sync_plugin, 'sync_{{ACCEPT}}_on_error' );
			return $admin_notice_callbacks;
		}
	);
}
